version: '3.8'
services:
  web:
    build: .
    #command: python /code/manage.py runserver 0.0.0.0:8000
    command: gunicorn enjoy_language.wsgi -b 0.0.0.0:8000
    environment:
      - ENVIRONMENT=production
      - SECRET_KEY=oij0o9g^=rr586g#z$$s63s2&kre&=57pn2hs*kh!cjj$$x_28z_
      - DEBUG=0
      - AWS_ACCESS_KEY_ID =AKIAVUYNQPEXUIWIVB2Q
      - AWS_SECRET_ACCESS_KEY =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
      - AWS_STORAGE_BUCKET_NAME =enjoy-language
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11
    ports:
      - "5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
